name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get the version
        run: echo ::set-output name=APP_VERSION::${GITHUB_REF#refs/tags/}

      - name: Copy .env environment
        run: cp .env.example .env

      - name: Build and publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          APP_API: ${{secrets.APP_API}}

        with:
          name: nghiepit/botble-graphql-next
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          buildargs: APP_VERSION,APP_API
